apiVersion: v1
kind: Service
metadata:
  name: flutter-web-service1
spec:
  type: LoadBalancer
  selector:
    app: flutter-web
  ports:
    - protocol: TCP
      name: '80'
      port: 80
      targetPort: 80